#ifndef _QX_QUICKSAMPLE_EXPORT_H
#define _QX_QUICKSAMPLE_EXPORT_H

#define QX_REGISTER_HPP_SMARTTERMINAL        QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_SMARTTERMINAL        QX_REGISTER_CPP_EXPORT_DLL

#endif // EXPORT_H
